#!/bin/bash
test

# special variables are $o to $9 , $@, &#, $$


echo "Printing Script Name : $0"

echo -e "Good Morning , Today date is  $DATE"
echo -e "Total number of sessions : \e[33m $NO_OF_SESSIONS \e[0m"